# Configuring CircleCI：https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  node: circleci/node@5.0.0
  browser-tools: circleci/browser-tools@1.2.4
  coveralls: coveralls/coveralls@1.0.6
  github-cli: circleci/github-cli@2.1.0

executors:
  docker:
    docker:
      - image: cimg/node:16.14-browsers

jobs:
  build:
    executor: docker
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Intsall latest packages
          command: |
            node ./scripts/upgrade.js
            npm install
      - run:
          name: Run tests
          command: |
            npm run prettier
            npm run lint
            npm run test
            npm run build
      - store_artifacts:
          path: ./package.json
      - store_artifacts:
          path: ./package-lock.json
workflows:
  upgrade:
    jobs:
      - build
