# Configuring CircleCI：https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.4
  coveralls: coveralls/coveralls@2.2.1
  github-cli: circleci/github-cli@2.2.0

executors:
  docker:
    docker:
      - image: cimg/node:16.20-browsers

jobs:
  build:
    executor: docker
    steps:
      - checkout
      - node/install-packages
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: User identity
          command: |
            git config --global user.email "atwwei@gmail.com"
            git config --global user.name "circleci"
            git remote set-url origin https://$GITHUB_TOKEN@github.com/atwwei/dfp
            echo //registry.npmjs.org/:_authToken=$NPM_TOKEN >> ~/.npmrc
      - run:
          name: Run test
          command: npm run test
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Prepare publish
          command: |
            set +e
            cd dist

            name=`npm pkg get name | sed 's/"//g'`
            version=`npm pkg get version | sed 's/"//g'`

            versions=`npm view ${name}@~${version} version 2>/dev/null | sed "s/.* //g" | sed "s/'//g"`
            if [[ "$versions" != "" ]]; then
                npm pkg set version=${versions##*[[:space:]]}
                npm version patch
            fi

            npm pkg delete scripts lint-staged dependencies.tslib devDependencies

            npm publish --access public --dry-run
      - when:
          condition:
            matches:
              pattern: ^(main|v\d+-lts)$
              value: << pipeline.git.branch >>
          steps:
            - run:
                name: Run publish
                command: |
                  if [[ $CIRCLE_BRANCH = "main" ]]; then
                    npm publish ./dist --access public
                  else
                    npm publish ./dist --access public --tag $CIRCLE_BRANCH
                  fi
                  git push --tags
            - coveralls/upload
      - store_test_results:
          path: reports
      - store_artifacts:
          path: dist
      - store_artifacts:
          path: coverage
workflows:
  dfp:
    jobs:
      - build
